### ISSUE TITLE
[FEATURE: QoL] Hijacking the right click in `playlists` menu

### ISSUE THREAD

**Issue by crackheadakira** [geoffrey45/alice-core#11]
(moved issue from server repo to client)

Currently when right clicking a playlist it just shows the regular context menu, which probably wouldn't be desirable on the playlists folder, as many people are used to being able to right click on a playlist and quickly delete it or rename it from there instead of having to open it up.
So preventing the default interaction and showing your own context menu for playlists would be a nice QoL feature, this could also be made to scale so you could easily replace the default context menu when needed.

**Comment by cwilvx** [comment]
I agree, that would be nice addition. This feature can be added alongside the feature to add a whole folder to a playlist planned for the third release (probably 2 weeks or less from now). The second release will add a feature that allows you to customise which directories you want to be scanned for music.

I'll let you know when this is ready for testing :)

**Comment by crackheadakira** [comment]
used the latest version of the app, saw that it was added when right clicking tracks in albums or playlists. so i'll be closing the issue.
