### ISSUE TITLE
Album track listing broken on mobile.

### ISSUE THREAD

**Issue by tunnull** [geoffrey45/alice-core#20]
When viewing an albums' tracks, the info for each track isn't laid out correctly. 
Example on Pixel 5:
https://media.discordapp.net/attachments/1169084883155566643/1174027880087441419/Screenshot_20231114-114702.png
![Broken Track Layout Image](https://media.discordapp.net/attachments/1169084883155566643/1174027880087441419/Screenshot_20231114-114702.png)

**Comment by cwilvx** [comment]
Hello @tunnull 

Thanks for reporting this issue. I'll will fix it.

**Comment by cwilvx** [comment]
Hello @tunnull 

I have fixed this issue. Please redownload the files from [the latest release](https://github.com/swing-opensource/swingmusic/releases/tag/v1.4.0). I have updated the files in the release. If you are using docker, you can re-pull [the latest tag](https://github.com/swing-opensource/swingmusic/pkgs/container/swingmusic/147615138?tag=v1.4.0).

Thanks for opening the issue.
