### ISSUE TITLE
Play button on playlist card

### ISSUE THREAD

**Issue by skilletfun** [geoffrey45/alice-core#36]
Hi!

I see some unfair thing: Artist card has play button, Album has one, Track also has one, but Playlist does not))
I mean while you hover card

Screenshots with examples (taken from Home tab):
Track with Play button while hover
![image](https://github.com/user-attachments/assets/a0639e8f-920d-4c13-87d3-ba57f8afac0b)

Playlist without Play button while hover
![image](https://github.com/user-attachments/assets/909c3885-c3ec-4cc4-aebd-4ffa029edcb3)

Please, add play button to the Playlist, it will safe a lot of time, at least for me

Thanks for you work!

**Comment by cwilvx** [comment]
Fixed by @skilletfun with linked pull request on webclient repo.

Thank you @skilletfun.
